# Generated by Django 4.2.27 on 2026-01-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester_role', models.CharField(choices=[('FIRE', 'Fire Commander'), ('EMS', 'EMS Commander'), ('POLICE', 'Police Commander')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('details', models.TextField()),
                ('priority', models.IntegerField(default=3)),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
        ),
    ]
