# Generated by Django 4.2.27 on 2026-01-17 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit_type', models.CharField(choices=[('AMB', 'Ambulance'), ('ENG', 'Engine')], max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('DISPATCHED', 'Dispatched'), ('TO_SCENE', 'In transit to scene'), ('ON_SCENE', 'On scene'), ('TO_HOSPITAL', 'In transit to hospital'), ('AT_HOSPITAL', 'At hospital'), ('OOS', 'Out of service')], default='AVAILABLE', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='details',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='requester_role',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='title',
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='requested_by_role',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='unit_type',
            field=models.CharField(choices=[('AMB', 'Ambulance'), ('ENG', 'Engine')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('PARTIAL', 'Partially fulfilled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='incidents.unit')),
            ],
        ),
        migrations.CreateModel(
            name='RequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='incidents.resourcerequest')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='incidents.unit')),
            ],
            options={
                'unique_together': {('request', 'unit')},
            },
        ),
    ]
