# Generated by Django 4.2.27 on 2026-01-17 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_unit_remove_resourcerequest_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='requestassignment',
            old_name='assigned_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='last_update',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='details',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='note',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='requested_by_role',
        ),
        migrations.AddField(
            model_name='logentry',
            name='from_status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='to_status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='priority',
            field=models.CharField(blank=True, default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='last_status_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('PARTIAL', 'Partially fulfilled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ENROUTE', 'Enroute to scene'), ('ON_SCENE', 'On scene'), ('TRANSPORTING', 'Transporting to hospital')], default='AVAILABLE', max_length=30),
        ),
    ]
