# Generated by Django 4.2.27 on 2026-01-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_rename_timestamp_logentry_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='last_status_at',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='updated_at',
        ),
    ]
